#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MEZ_Production")]
public partial class MainDataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public MainDataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MEZ_ProductionConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public MainDataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MainDataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MainDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MainDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_SelectProductWithUnits")]
	public ISingleResult<ogk_SelectProductWithUnitsResult> ogk_SelectProductWithUnits([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentID", DbType="Int")] System.Nullable<int> parentID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ArticleID", DbType="Int")] System.Nullable<int> articleID)
	{
		//IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parentID, articleID);
		//return ((ISingleResult<ogk_SelectProductWithUnitsResult>)(result.ReturnValue));
	    return null;
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_SelectScale")]
	public ISingleResult<ogk_SelectScaleResult> ogk_SelectScale([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
		return ((ISingleResult<ogk_SelectScaleResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_SelectUnits")]
	public ISingleResult<ogk_SelectUnitsResult> ogk_SelectUnits()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<ogk_SelectUnitsResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_SelectProductionTypes")]
	public ISingleResult<ogk_SelectProductionTypesResult> ogk_SelectProductionTypes()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<ogk_SelectProductionTypesResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_GetArticleChildren", IsComposable=true)]
	public System.Nullable<int> ogk_GetArticleChildren([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
	{
        //return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD).ReturnValue));
	    if (iD == 4 || iD == 8 || iD == 14)
	    {
	        return 3;
        }

	    return 0;

	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_AddArticleGroup")]
	public int ogk_AddArticleGroup([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PARENT_ID", DbType="Int")] System.Nullable<int> pARENT_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NAME", DbType="NVarChar(MAX)")] string nAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PREFIX", DbType="NVarChar(MAX)")] string pREFIX, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TYPE_ID", DbType="Int")] System.Nullable<int> tYPE_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pARENT_ID, nAME, pREFIX, tYPE_ID);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_RemoveArticleGroup")]
	public int ogk_RemoveArticleGroup([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_EditArticleGroup")]
	public int ogk_EditArticleGroup([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NAME", DbType="NVarChar(MAX)")] string nAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PREFIX", DbType="NVarChar(MAX)")] string pREFIX)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, nAME, pREFIX);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_GroupNameCheckUpGetID", IsComposable=true)]
	public System.Nullable<int> ogk_GroupNameCheckUpGetID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GroupName", DbType="NVarChar(MAX)")] string groupName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentGroupID", DbType="Int")] System.Nullable<int> parentGroupID)
	{
		return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), groupName, parentGroupID).ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_SelectArticleTypes")]
	public ISingleResult<ogk_SelectArticleTypesResult> ogk_SelectArticleTypes()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<ogk_SelectArticleTypesResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_SelectArticleTypesForGroups")]
	public ISingleResult<ogk_SelectArticleTypesForGroupsResult> ogk_SelectArticleTypesForGroups()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<ogk_SelectArticleTypesForGroupsResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_MoveArticleGroup")]
	public int ogk_MoveArticleGroup([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PARENT_ID", DbType="Int")] System.Nullable<int> pARENT_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, pARENT_ID);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_SelectArticleGroups")]
	public ISingleResult<ogk_SelectArticleGroupsResult> ogk_SelectArticleGroups([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PARENT_ID", DbType="Int")] System.Nullable<int> pARENT_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TYPE_ID", DbType="Int")] System.Nullable<int> tYPE_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pARENT_ID, tYPE_ID);
		return ((ISingleResult<ogk_SelectArticleGroupsResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_SelectProductionArticles")]
	public ISingleResult<ogk_SelectProductionArticlesResult> ogk_SelectProductionArticles([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TYPE_ID", DbType="Int")] System.Nullable<int> tYPE_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tYPE_ID);
		return ((ISingleResult<ogk_SelectProductionArticlesResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_SelectArticlesOfGroup")]
	public ISingleResult<ogk_SelectArticlesOfGroupResult> ogk_SelectArticlesOfGroup([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GROUP_ID", DbType="Int")] System.Nullable<int> gROUP_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TYPE_ID", DbType="Int")] System.Nullable<int> tYPE_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gROUP_ID, tYPE_ID);
		return ((ISingleResult<ogk_SelectArticlesOfGroupResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_AddArticle")]
	public int ogk_AddArticle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NAME", DbType="NVarChar(MAX)")] string nAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DRAWING", DbType="NVarChar(MAX)")] string dRAWING, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GROUP_ID", DbType="Int")] System.Nullable<int> gROUP_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRICE", DbType="Money")] System.Nullable<decimal> pRICE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TYPE_ID", DbType="Int")] System.Nullable<int> tYPE_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nAME, dRAWING, gROUP_ID, pRICE, tYPE_ID);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_SelectArticle")]
	public ISingleResult<ogk_SelectArticleResult> ogk_SelectArticle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
		return ((ISingleResult<ogk_SelectArticleResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_EditArticle")]
	public int ogk_EditArticle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NAME", DbType="NVarChar(MAX)")] string nAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DRAWING", DbType="NVarChar(MAX)")] string dRAWING, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GROUP_ID", DbType="Int")] System.Nullable<int> gROUP_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRICE", DbType="Money")] System.Nullable<decimal> pRICE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TYPE_ID", DbType="Int")] System.Nullable<int> tYPE_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, nAME, dRAWING, gROUP_ID, pRICE, tYPE_ID);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_GetProductsCountForArticleGroup", IsComposable=true)]
	public System.Nullable<int> ogk_GetProductsCountForArticleGroup([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
	{
		return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD).ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_GetArticleParentsCount", IsComposable=true)]
	public System.Nullable<int> ogk_GetArticleParentsCount([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
	{
		return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD).ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_SelectProductionTreeChildren")]
	public ISingleResult<ogk_SelectProductionTreeChildrenResult> ogk_SelectProductionTreeChildren([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ARTICLE_ID", DbType="Int")] System.Nullable<int> aRTICLE_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aRTICLE_ID);
		return ((ISingleResult<ogk_SelectProductionTreeChildrenResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_SelectProduct")]
	public ISingleResult<ogk_SelectProductResult> ogk_SelectProduct([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ARTICLE_ID", DbType="Int")] System.Nullable<int> aRTICLE_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aRTICLE_ID);
		return ((ISingleResult<ogk_SelectProductResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_EditProductionTreeItem")]
	public int ogk_EditProductionTreeItem([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OUTER_PRODUCT_ID", DbType="Int")] System.Nullable<int> oUTER_PRODUCT_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="INNER_PRODUCT_ID", DbType="Int")] System.Nullable<int> iNNER_PRODUCT_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QUANTITY", DbType="BigInt")] System.Nullable<long> qUANTITY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UNIT_ID", DbType="Int")] System.Nullable<int> uNIT_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), oUTER_PRODUCT_ID, iNNER_PRODUCT_ID, qUANTITY, uNIT_ID);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_GetDefaultProductionUnitID", IsComposable=true)]
	public System.Nullable<int> ogk_GetDefaultProductionUnitID()
	{
		return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_GroupProducts")]
	public int ogk_GroupProducts([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OUTER_PRODUCT_ID", DbType="Int")] System.Nullable<int> oUTER_PRODUCT_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="INNER_PRODUCT_ID", DbType="Int")] System.Nullable<int> iNNER_PRODUCT_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QUANTITY", DbType="BigInt")] System.Nullable<long> qUANTITY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UNIT_ID", DbType="Int")] System.Nullable<int> uNIT_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), oUTER_PRODUCT_ID, iNNER_PRODUCT_ID, qUANTITY, uNIT_ID);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_UngroupProducts")]
	public int ogk_UngroupProducts([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OUTER_PRODUCT_ID", DbType="Int")] System.Nullable<int> oUTER_PRODUCT_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="INNER_PRODUCT_ID", DbType="Int")] System.Nullable<int> iNNER_PRODUCT_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), oUTER_PRODUCT_ID, iNNER_PRODUCT_ID);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_RemoveArticle")]
	public int ogk_RemoveArticle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_DrawingAndNameCheckUpCreate")]
	public ISingleResult<ogk_DrawingAndNameCheckUpCreateResult> ogk_DrawingAndNameCheckUpCreate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Drawing", DbType="NVarChar(MAX)")] string drawing, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string productName)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), drawing, productName);
		return ((ISingleResult<ogk_DrawingAndNameCheckUpCreateResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_DrawingAndNameCheckUpEdit")]
	public ISingleResult<ogk_DrawingAndNameCheckUpEditResult> ogk_DrawingAndNameCheckUpEdit([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Drawing", DbType="NVarChar(MAX)")] string drawing, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> productID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string productName)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), drawing, productID, productName);
		return ((ISingleResult<ogk_DrawingAndNameCheckUpEditResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_GetGroupChildrenCount", IsComposable=true)]
	public System.Nullable<int> ogk_GetGroupChildrenCount([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
	{
		return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD).ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_SearchForProductionArticle")]
	public ISingleResult<ogk_SearchForProductionArticleResult> ogk_SearchForProductionArticle([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NAME_PATTERN", DbType="NVarChar(MAX)")] string nAME_PATTERN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DRAWING_PATTERN", DbType="NVarChar(MAX)")] string dRAWING_PATTERN)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nAME_PATTERN, dRAWING_PATTERN);
		return ((ISingleResult<ogk_SearchForProductionArticleResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_SearchForProductionArticleDrawing")]
	public ISingleResult<ogk_SearchForProductionArticleDrawingResult> ogk_SearchForProductionArticleDrawing([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PATTERN", DbType="NVarChar(MAX)")] string pATTERN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="COUNT", DbType="Int")] System.Nullable<int> cOUNT)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pATTERN, cOUNT);
		return ((ISingleResult<ogk_SearchForProductionArticleDrawingResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_SearchForProductionArticleName")]
	public ISingleResult<ogk_SearchForProductionArticleNameResult> ogk_SearchForProductionArticleName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PATTERN", DbType="NVarChar(MAX)")] string pATTERN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="COUNT", DbType="Int")] System.Nullable<int> cOUNT)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pATTERN, cOUNT);
		return ((ISingleResult<ogk_SearchForProductionArticleNameResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_SearchForProductionArticleName_All")]
	public ISingleResult<ogk_SearchForProductionArticleName_AllResult> ogk_SearchForProductionArticleName_All([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PATTERN", DbType="NVarChar(MAX)")] string pATTERN)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pATTERN);
		return ((ISingleResult<ogk_SearchForProductionArticleName_AllResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_SelectArticleGroup")]
	public ISingleResult<ogk_SelectArticleGroupResult> ogk_SelectArticleGroup([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
		return ((ISingleResult<ogk_SelectArticleGroupResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_GroupNameCheckUp", IsComposable=true)]
	public System.Nullable<int> ogk_GroupNameCheckUp([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GroupName", DbType="NVarChar(MAX)")] string groupName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentGroupID", DbType="Int")] System.Nullable<int> parentGroupID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ArticleTypeID", DbType="Int")] System.Nullable<int> articleTypeID)
	{
		return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), groupName, parentGroupID, articleTypeID).ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_GetArticleProductionType", IsComposable=true)]
	public System.Nullable<int> ogk_GetArticleProductionType([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
	{
		return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD).ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_GetArticleParents")]
	public ISingleResult<ogk_GetArticleParentsResult> ogk_GetArticleParents([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
		return ((ISingleResult<ogk_GetArticleParentsResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_CTE_DEMO")]
	public ISingleResult<ogk_CTE_DEMOResult> ogk_CTE_DEMO()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<ogk_CTE_DEMOResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_GetProductSpecification")]
	public ISingleResult<ogk_GetProductSpecificationResult> ogk_GetProductSpecification([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRODUCT_ID", DbType="Int")] System.Nullable<int> pRODUCT_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pRODUCT_ID);
		return ((ISingleResult<ogk_GetProductSpecificationResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_ChangeParent")]
	public int ogk_ChangeParent([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OUTER_PRODUCT_ID", DbType="Int")] System.Nullable<int> oUTER_PRODUCT_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="INNER_PRODUCT_ID", DbType="Int")] System.Nullable<int> iNNER_PRODUCT_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NEW_OUTER_PRODUCT_ID", DbType="Int")] System.Nullable<int> nEW_OUTER_PRODUCT_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), oUTER_PRODUCT_ID, iNNER_PRODUCT_ID, nEW_OUTER_PRODUCT_ID);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ogk_GetUsers")]
	public ISingleResult<ogk_GetUsersResult> ogk_GetUsers()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<ogk_GetUsersResult>)(result.ReturnValue));
	}
}

public partial class ogk_SelectProductWithUnitsResult
{
	
	private int _ID;
	
	private string _NAME;
	
	private string _TYPE;
	
	private string _DRAWING;
	
	private string _UNIT;
	
	private int _SCALE;
	
	private System.Nullable<double> _QUANTITY;
	
	private int _UNIT_ID;
	
	public ogk_SelectProductWithUnitsResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(MAX)")]
	public string NAME
	{
		get
		{
			return this._NAME;
		}
		set
		{
			if ((this._NAME != value))
			{
				this._NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string TYPE
	{
		get
		{
			return this._TYPE;
		}
		set
		{
			if ((this._TYPE != value))
			{
				this._TYPE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRAWING", DbType="NVarChar(MAX)")]
	public string DRAWING
	{
		get
		{
			return this._DRAWING;
		}
		set
		{
			if ((this._DRAWING != value))
			{
				this._DRAWING = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string UNIT
	{
		get
		{
			return this._UNIT;
		}
		set
		{
			if ((this._UNIT != value))
			{
				this._UNIT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCALE", DbType="Int NOT NULL")]
	public int SCALE
	{
		get
		{
			return this._SCALE;
		}
		set
		{
			if ((this._SCALE != value))
			{
				this._SCALE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Float")]
	public System.Nullable<double> QUANTITY
	{
		get
		{
			return this._QUANTITY;
		}
		set
		{
			if ((this._QUANTITY != value))
			{
				this._QUANTITY = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_ID", DbType="Int NOT NULL")]
	public int UNIT_ID
	{
		get
		{
			return this._UNIT_ID;
		}
		set
		{
			if ((this._UNIT_ID != value))
			{
				this._UNIT_ID = value;
			}
		}
	}
}

public partial class ogk_SelectScaleResult
{
	
	private int _SCALE;
	
	public ogk_SelectScaleResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCALE", DbType="Int NOT NULL")]
	public int SCALE
	{
		get
		{
			return this._SCALE;
		}
		set
		{
			if ((this._SCALE != value))
			{
				this._SCALE = value;
			}
		}
	}
}

public partial class ogk_SelectUnitsResult
{
	
	private int _ID;
	
	private string _NAME;
	
	public ogk_SelectUnitsResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string NAME
	{
		get
		{
			return this._NAME;
		}
		set
		{
			if ((this._NAME != value))
			{
				this._NAME = value;
			}
		}
	}
}

public partial class ogk_SelectProductionTypesResult
{
	
	private int _ID;
	
	private string _NAME;
	
	public ogk_SelectProductionTypesResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string NAME
	{
		get
		{
			return this._NAME;
		}
		set
		{
			if ((this._NAME != value))
			{
				this._NAME = value;
			}
		}
	}
}

public partial class ogk_SelectArticleTypesResult
{
	
	private int _ID;
	
	private string _NAME;
	
	public ogk_SelectArticleTypesResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string NAME
	{
		get
		{
			return this._NAME;
		}
		set
		{
			if ((this._NAME != value))
			{
				this._NAME = value;
			}
		}
	}
}

public partial class ogk_SelectArticleTypesForGroupsResult
{
	
	private int _ID;
	
	private string _NAME;
	
	public ogk_SelectArticleTypesForGroupsResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string NAME
	{
		get
		{
			return this._NAME;
		}
		set
		{
			if ((this._NAME != value))
			{
				this._NAME = value;
			}
		}
	}
}

public partial class ogk_SelectArticleGroupsResult
{
	
	private int _ID;
	
	private string _NAME;
	
	private string _PREFIX;
	
	public ogk_SelectArticleGroupsResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string NAME
	{
		get
		{
			return this._NAME;
		}
		set
		{
			if ((this._NAME != value))
			{
				this._NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREFIX", DbType="NVarChar(MAX)")]
	public string PREFIX
	{
		get
		{
			return this._PREFIX;
		}
		set
		{
			if ((this._PREFIX != value))
			{
				this._PREFIX = value;
			}
		}
	}
}

public partial class ogk_SelectProductionArticlesResult
{
	
	private int _ID;
	
	private string _NAME;
	
	private int _ORDER_NUMBER;
	
	private string _DRAWING;
	
	private decimal _SELF_PRICE;
	
	private decimal _OTHERS_PRICE;
	
	public ogk_SelectProductionArticlesResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string NAME
	{
		get
		{
			return this._NAME;
		}
		set
		{
			if ((this._NAME != value))
			{
				this._NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDER_NUMBER", DbType="Int NOT NULL")]
	public int ORDER_NUMBER
	{
		get
		{
			return this._ORDER_NUMBER;
		}
		set
		{
			if ((this._ORDER_NUMBER != value))
			{
				this._ORDER_NUMBER = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRAWING", DbType="NVarChar(MAX)")]
	public string DRAWING
	{
		get
		{
			return this._DRAWING;
		}
		set
		{
			if ((this._DRAWING != value))
			{
				this._DRAWING = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SELF_PRICE", DbType="Money NOT NULL")]
	public decimal SELF_PRICE
	{
		get
		{
			return this._SELF_PRICE;
		}
		set
		{
			if ((this._SELF_PRICE != value))
			{
				this._SELF_PRICE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OTHERS_PRICE", DbType="Money NOT NULL")]
	public decimal OTHERS_PRICE
	{
		get
		{
			return this._OTHERS_PRICE;
		}
		set
		{
			if ((this._OTHERS_PRICE != value))
			{
				this._OTHERS_PRICE = value;
			}
		}
	}
}

public partial class ogk_SelectArticlesOfGroupResult
{
	
	private int _ID;
	
	private string _NAME;
	
	private string _DRAWING;
	
	public ogk_SelectArticlesOfGroupResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string NAME
	{
		get
		{
			return this._NAME;
		}
		set
		{
			if ((this._NAME != value))
			{
				this._NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRAWING", DbType="NVarChar(MAX)")]
	public string DRAWING
	{
		get
		{
			return this._DRAWING;
		}
		set
		{
			if ((this._DRAWING != value))
			{
				this._DRAWING = value;
			}
		}
	}
}

public partial class ogk_SelectArticleResult
{
	
	private int _ID;
	
	private string _NAME;
	
	private string _DRAWING;
	
	private decimal _SELF_PRICE;
	
	private int _TYPE;
	
	private System.Nullable<int> _PRODUCTION_GROUP_ID;
	
	public ogk_SelectArticleResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string NAME
	{
		get
		{
			return this._NAME;
		}
		set
		{
			if ((this._NAME != value))
			{
				this._NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRAWING", DbType="NVarChar(MAX)")]
	public string DRAWING
	{
		get
		{
			return this._DRAWING;
		}
		set
		{
			if ((this._DRAWING != value))
			{
				this._DRAWING = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SELF_PRICE", DbType="Money NOT NULL")]
	public decimal SELF_PRICE
	{
		get
		{
			return this._SELF_PRICE;
		}
		set
		{
			if ((this._SELF_PRICE != value))
			{
				this._SELF_PRICE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="Int NOT NULL")]
	public int TYPE
	{
		get
		{
			return this._TYPE;
		}
		set
		{
			if ((this._TYPE != value))
			{
				this._TYPE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTION_GROUP_ID", DbType="Int")]
	public System.Nullable<int> PRODUCTION_GROUP_ID
	{
		get
		{
			return this._PRODUCTION_GROUP_ID;
		}
		set
		{
			if ((this._PRODUCTION_GROUP_ID != value))
			{
				this._PRODUCTION_GROUP_ID = value;
			}
		}
	}
}

public partial class ogk_SelectProductionTreeChildrenResult
{
	
	private int _ID;
	
	private int _PARENT_ID;
	
	private int _CHILD_ID;
	
	private string _NAME;
	
	private string _DRAWING;
	
	private long _QUANTITY;
	
	private string _TYPE_CODE;
	
	private string _TYPE_NAME;
	
	private int _UNIT_ID;
	
	private int _UNIT_SCALE;
	
	private string _QUANTITY_TEXT;
	
	public ogk_SelectProductionTreeChildrenResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_ID", DbType="Int NOT NULL")]
	public int PARENT_ID
	{
		get
		{
			return this._PARENT_ID;
		}
		set
		{
			if ((this._PARENT_ID != value))
			{
				this._PARENT_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHILD_ID", DbType="Int NOT NULL")]
	public int CHILD_ID
	{
		get
		{
			return this._CHILD_ID;
		}
		set
		{
			if ((this._CHILD_ID != value))
			{
				this._CHILD_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(MAX)")]
	public string NAME
	{
		get
		{
			return this._NAME;
		}
		set
		{
			if ((this._NAME != value))
			{
				this._NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRAWING", DbType="NVarChar(MAX)")]
	public string DRAWING
	{
		get
		{
			return this._DRAWING;
		}
		set
		{
			if ((this._DRAWING != value))
			{
				this._DRAWING = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="BigInt NOT NULL")]
	public long QUANTITY
	{
		get
		{
			return this._QUANTITY;
		}
		set
		{
			if ((this._QUANTITY != value))
			{
				this._QUANTITY = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE_CODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string TYPE_CODE
	{
		get
		{
			return this._TYPE_CODE;
		}
		set
		{
			if ((this._TYPE_CODE != value))
			{
				this._TYPE_CODE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE_NAME", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string TYPE_NAME
	{
		get
		{
			return this._TYPE_NAME;
		}
		set
		{
			if ((this._TYPE_NAME != value))
			{
				this._TYPE_NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_ID", DbType="Int NOT NULL")]
	public int UNIT_ID
	{
		get
		{
			return this._UNIT_ID;
		}
		set
		{
			if ((this._UNIT_ID != value))
			{
				this._UNIT_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_SCALE", DbType="Int NOT NULL")]
	public int UNIT_SCALE
	{
		get
		{
			return this._UNIT_SCALE;
		}
		set
		{
			if ((this._UNIT_SCALE != value))
			{
				this._UNIT_SCALE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY_TEXT", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string QUANTITY_TEXT
	{
		get
		{
			return this._QUANTITY_TEXT;
		}
		set
		{
			if ((this._QUANTITY_TEXT != value))
			{
				this._QUANTITY_TEXT = value;
			}
		}
	}
}

public partial class ogk_SelectProductResult
{
	
	private int _ID;
	
	private string _NAME;
	
	private string _DRAWING;
	
	private string _TYPE_CODE;
	
	private string _TYPE_NAME;
	
	public ogk_SelectProductResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string NAME
	{
		get
		{
			return this._NAME;
		}
		set
		{
			if ((this._NAME != value))
			{
				this._NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRAWING", DbType="NVarChar(MAX)")]
	public string DRAWING
	{
		get
		{
			return this._DRAWING;
		}
		set
		{
			if ((this._DRAWING != value))
			{
				this._DRAWING = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE_CODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string TYPE_CODE
	{
		get
		{
			return this._TYPE_CODE;
		}
		set
		{
			if ((this._TYPE_CODE != value))
			{
				this._TYPE_CODE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE_NAME", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string TYPE_NAME
	{
		get
		{
			return this._TYPE_NAME;
		}
		set
		{
			if ((this._TYPE_NAME != value))
			{
				this._TYPE_NAME = value;
			}
		}
	}
}

public partial class ogk_DrawingAndNameCheckUpCreateResult
{
	
	private int _ID;
	
	public ogk_DrawingAndNameCheckUpCreateResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
}

public partial class ogk_DrawingAndNameCheckUpEditResult
{
	
	private int _ID;
	
	public ogk_DrawingAndNameCheckUpEditResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
}

public partial class ogk_SearchForProductionArticleResult
{
	
	private int _ID;
	
	private string _NAME;
	
	private string _DRAWING;
	
	private string _TYPE_NAME;
	
	public ogk_SearchForProductionArticleResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(MAX)")]
	public string NAME
	{
		get
		{
			return this._NAME;
		}
		set
		{
			if ((this._NAME != value))
			{
				this._NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRAWING", DbType="NVarChar(MAX)")]
	public string DRAWING
	{
		get
		{
			return this._DRAWING;
		}
		set
		{
			if ((this._DRAWING != value))
			{
				this._DRAWING = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE_NAME", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string TYPE_NAME
	{
		get
		{
			return this._TYPE_NAME;
		}
		set
		{
			if ((this._TYPE_NAME != value))
			{
				this._TYPE_NAME = value;
			}
		}
	}
}

public partial class ogk_SearchForProductionArticleDrawingResult
{
	
	private string _DRAWING;
	
	public ogk_SearchForProductionArticleDrawingResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRAWING", DbType="NVarChar(MAX)")]
	public string DRAWING
	{
		get
		{
			return this._DRAWING;
		}
		set
		{
			if ((this._DRAWING != value))
			{
				this._DRAWING = value;
			}
		}
	}
}

public partial class ogk_SearchForProductionArticleNameResult
{
	
	private string _NAME;
	
	public ogk_SearchForProductionArticleNameResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(MAX)")]
	public string NAME
	{
		get
		{
			return this._NAME;
		}
		set
		{
			if ((this._NAME != value))
			{
				this._NAME = value;
			}
		}
	}
}

public partial class ogk_SearchForProductionArticleName_AllResult
{
	
	private int _ID;
	
	private string _NAME;
	
	private string _DRAWING;
	
	private string _TYPE_NAME;
	
	public ogk_SearchForProductionArticleName_AllResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(MAX)")]
	public string NAME
	{
		get
		{
			return this._NAME;
		}
		set
		{
			if ((this._NAME != value))
			{
				this._NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRAWING", DbType="NVarChar(MAX)")]
	public string DRAWING
	{
		get
		{
			return this._DRAWING;
		}
		set
		{
			if ((this._DRAWING != value))
			{
				this._DRAWING = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE_NAME", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string TYPE_NAME
	{
		get
		{
			return this._TYPE_NAME;
		}
		set
		{
			if ((this._TYPE_NAME != value))
			{
				this._TYPE_NAME = value;
			}
		}
	}
}

public partial class ogk_SelectArticleGroupResult
{
	
	private int _ID;
	
	private string _NAME;
	
	private int _PARENT_ID;
	
	public ogk_SelectArticleGroupResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string NAME
	{
		get
		{
			return this._NAME;
		}
		set
		{
			if ((this._NAME != value))
			{
				this._NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_ID", DbType="Int NOT NULL")]
	public int PARENT_ID
	{
		get
		{
			return this._PARENT_ID;
		}
		set
		{
			if ((this._PARENT_ID != value))
			{
				this._PARENT_ID = value;
			}
		}
	}
}

public partial class ogk_GetArticleParentsResult
{
	
	private int _ID;
	
	private string _NAME;
	
	private string _DRAWING;
	
	private int _TYPE;
	
	public ogk_GetArticleParentsResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string NAME
	{
		get
		{
			return this._NAME;
		}
		set
		{
			if ((this._NAME != value))
			{
				this._NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRAWING", DbType="NVarChar(MAX)")]
	public string DRAWING
	{
		get
		{
			return this._DRAWING;
		}
		set
		{
			if ((this._DRAWING != value))
			{
				this._DRAWING = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="Int NOT NULL")]
	public int TYPE
	{
		get
		{
			return this._TYPE;
		}
		set
		{
			if ((this._TYPE != value))
			{
				this._TYPE = value;
			}
		}
	}
}

public partial class ogk_CTE_DEMOResult
{
	
	private string _ARTICLE_NAME;
	
	private string _ARTICLE_GROUP_NAME;
	
	private string _COMPONENT_NAME;
	
	private System.Nullable<double> _QUANTITY;
	
	private string _UNIT_NAME;
	
	public ogk_CTE_DEMOResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARTICLE_NAME", DbType="NVarChar(MAX)")]
	public string ARTICLE_NAME
	{
		get
		{
			return this._ARTICLE_NAME;
		}
		set
		{
			if ((this._ARTICLE_NAME != value))
			{
				this._ARTICLE_NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARTICLE_GROUP_NAME", DbType="VarChar(MAX)")]
	public string ARTICLE_GROUP_NAME
	{
		get
		{
			return this._ARTICLE_GROUP_NAME;
		}
		set
		{
			if ((this._ARTICLE_GROUP_NAME != value))
			{
				this._ARTICLE_GROUP_NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPONENT_NAME", DbType="NVarChar(MAX)")]
	public string COMPONENT_NAME
	{
		get
		{
			return this._COMPONENT_NAME;
		}
		set
		{
			if ((this._COMPONENT_NAME != value))
			{
				this._COMPONENT_NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Float")]
	public System.Nullable<double> QUANTITY
	{
		get
		{
			return this._QUANTITY;
		}
		set
		{
			if ((this._QUANTITY != value))
			{
				this._QUANTITY = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_NAME", DbType="NVarChar(MAX)")]
	public string UNIT_NAME
	{
		get
		{
			return this._UNIT_NAME;
		}
		set
		{
			if ((this._UNIT_NAME != value))
			{
				this._UNIT_NAME = value;
			}
		}
	}
}

public partial class ogk_GetProductSpecificationResult
{
	
	private string _ARTICLE_NAME;
	
	private string _ARTICLE_GROUP_NAME;
	
	private string _COMPONENT_NAME;
	
	private System.Nullable<double> _QUANTITY;
	
	private string _UNIT_NAME;
	
	private string _DRAWING;
	
	public ogk_GetProductSpecificationResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARTICLE_NAME", DbType="NVarChar(MAX)")]
	public string ARTICLE_NAME
	{
		get
		{
			return this._ARTICLE_NAME;
		}
		set
		{
			if ((this._ARTICLE_NAME != value))
			{
				this._ARTICLE_NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARTICLE_GROUP_NAME", DbType="VarChar(MAX)")]
	public string ARTICLE_GROUP_NAME
	{
		get
		{
			return this._ARTICLE_GROUP_NAME;
		}
		set
		{
			if ((this._ARTICLE_GROUP_NAME != value))
			{
				this._ARTICLE_GROUP_NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPONENT_NAME", DbType="NVarChar(MAX)")]
	public string COMPONENT_NAME
	{
		get
		{
			return this._COMPONENT_NAME;
		}
		set
		{
			if ((this._COMPONENT_NAME != value))
			{
				this._COMPONENT_NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Float")]
	public System.Nullable<double> QUANTITY
	{
		get
		{
			return this._QUANTITY;
		}
		set
		{
			if ((this._QUANTITY != value))
			{
				this._QUANTITY = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIT_NAME", DbType="NVarChar(MAX)")]
	public string UNIT_NAME
	{
		get
		{
			return this._UNIT_NAME;
		}
		set
		{
			if ((this._UNIT_NAME != value))
			{
				this._UNIT_NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRAWING", DbType="NVarChar(MAX)")]
	public string DRAWING
	{
		get
		{
			return this._DRAWING;
		}
		set
		{
			if ((this._DRAWING != value))
			{
				this._DRAWING = value;
			}
		}
	}
}

public partial class ogk_GetUsersResult
{
	
	private string _NAME;
	
	public ogk_GetUsersResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string NAME
	{
		get
		{
			return this._NAME;
		}
		set
		{
			if ((this._NAME != value))
			{
				this._NAME = value;
			}
		}
	}
}
#pragma warning restore 1591
